services:
  arti:
    build:
      context: .
      args:
        VERSION: "${ARTI_VERSION:-latest}"
    platform: "${PLATFORM:-linux/amd64}"
    ports:
      - "${SOCKS_PORT:-9150}:${SOCKS_PORT:-9150}"
    environment:
      - SOCKS_PORT=${SOCKS_PORT:-9150}
    volumes:
      - arti-cache:/var/cache/arti
      - arti-state:/var/lib/arti
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    restart: unless-stopped

volumes:
  arti-cache:
  arti-state:
