FROM alpine:3.22
RUN apk add --no-cache privoxy curl
COPY docker/privoxy.conf /etc/privoxy/config.tpl
COPY docker/privoxy-entrypoint.sh /usr/local/bin/privoxy-entrypoint.sh
RUN chmod +x /usr/local/bin/privoxy-entrypoint.sh
EXPOSE 8118
ENTRYPOINT ["/usr/local/bin/privoxy-entrypoint.sh"]
